- public/custom-options.html
- src/Main.elm
- src/Option.elm
- src/Ports.elm
- src/SelectionMode.elm
- src/much-select.js
Adding the `customValueSelected` event.
Don't show the "Add <whatever>..." option if the search string is an exact match for one of the existing options.
> Custom Options in single select: event

- public/events.html
- src/Main.elm
- src/Ports.elm
- src/much-select.js
When deselecting an option in a single select, emit a `deselectItem` CustomEvent that include the deselected options value and label.
In the sandbox:
> deselectItem Custom Event

- public/event-logger.js
- public/events.html
- public/index.html
- src/much-select.js
This should address #44.
This finishes up the example of persisting custom examples and re-adding them next time the page is loaded.
I also added an example for the `muchSelectReady` event which was needed.
> Example saving a custom option

- src/much-select.js
- tests/Attributes/selected-value.test.html
- tests/Slots/select-input-slot.test.html
If a selected value is empty and we're doing json encoding, there were a couple bugs.
Adding unit tests for this behavior too.
> Fixing json-encoded empty selected values

- public/multi-select.html
- src/Main.elm
- src/much-select.js
- tests/IntegrationTests/options.test.html
Fixes #56
Changing up the markup a bit for the buttons (in the `value` s) to deselected the selected options (in multi select mode)
Adding an example.
https://user-images.githubusercontent.com/42679/152610208-05a93e3a-04ae-428c-8799-c2fedf501225.mov
> An example for the multi-select-single-item-removal attribute

- src/Main.elm
- src/Ports.elm
- src/much-select.js
During the initialization process, if we parse the `select-input` slot and end up updating the options and the selected value as part of that process, we do not want to emit a `value-changed` event as part of that process.
> Do not emmit `value-changed` event durring initalization

- elm-tooling.json
- elm.json
- src/Option.elm
- src/OptionSearchFilter.elm
- src/OptionSearcher.elm
- tests/FilteringOptions/MaxNumberOfDropdownItems.elm
Once a user starts searching for an option, be more aggressive at **not** showing options that don't match very well.
Before: 
https://user-images.githubusercontent.com/42679/156834658-f17d04a3-91d1-49a6-ba29-cdba7e4b51fb.mov
After:
https://user-images.githubusercontent.com/42679/156834705-48b93ada-e5e6-40eb-a33a-6a476774db50.mov
> 98 filtering could be better

- public/multi-select-examples/custom-options.html
- src/Main.elm
- src/OptionSearchFilter.elm
From looking at the following example we need to allow propagation of the mouse down event in order for it to really prevent all the other click events from causing the input to lose focus triggering the blur event.
https://codepen.io/mudassir0909/pen/qBjvzL
There's also a bug fix here related to #98. There's an issue where if there's a custom option that one _always_ shows up as the best match. I fixed that by making the filtering a little bit more relaxed.
> 106: don't stop propegatin

- README.md
- public/attributes.html
- public/index.html
- src/Main.elm
- src/Ports.elm
- src/much-select.js
- tests/Attributes/search-string-minimum-length.test.html
- tests/IntegrationTests/DisplayingOptions.elm
The `search-string-minimum-length` attribute is used to manage how many characters a user needs to type in the `#input-filter` before the options in the dropdown start being filtered.
> 115: Add the search-string-minium-length attribute

- README.md
- public/slots.html
- src/Main.elm
- src/OptionSearcher.elm
If a user types in a search filter that's just totally bonkers (has no good matches) show a message saying there are no good search results.
The previous behavior was just to switch back to showing all the options.
> 116 bad search results just show everything

- elm.json
- public/example-partials/multi-select.html
- public/index.html
- public/multi-select-example.html
- src/Main.elm
- src/much-select.js
I managed to fix 2 related bugs in this PR. Both of them have to do with how events work.
1. The dropdown indicator (which should also act like a button) would not close the dropdown (unfocus).
2. Using the mouse to select text while filtering was not working. You could but you couldn't select, to delete or copy and paste.
A misc thing I did was break out another example so it could be opened on it's own.
> Clicking the on the close dropdown button is not working

- public/example-partials/change-select-attribute-changes-selected-value-in-much-select.html
- public/remote-api-example.html
- src/Main.elm
- src/Option.elm
- tests/Option/ReplacingOptions.elm
Ensure that only 1 option is selected in single select mode when replacing options.
Updating the example too, to remove any selected attributes from options
that are not Moe.
> Fix the example for selecting an option by changing the DOM.

- public/output-style-datalist-single-select.html
- public/output-style-datalist.html
- src/Main.elm
- src/TransformAndValidate.elm
- src/much-select.js
- tests/Events/Kepress.elm
- tests/Option/SelectedOptionOrdering.elm
Fixing a bug that causes `<much-select>` with `output-style="datalist"` to not emit events for key presses.
Adding a standalone example for Datalist Single Select
> 185 elm demo filtered options for datalist

- src/Main.elm
This is a follow up to https://github.com/DripEmail/much-select-elm/pull/195
After poking around a bit I realized if I clicked on the very bottom of the `<much-select>` I'd end up selecting the first item in the drop down (this in with the Drip styles).
So this is yet another case where we don't want to actually do "the thing" until mouse up.
> When focusing with a click, don't actually focus until mouse up.

- dist/much-select-debug.js
- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- dist/much-select.js
- src/MuchSelect.elm
- src/OptionsUtilities.elm
- src/much-select.js
To see the changes here you need to be in multi select mode.
We do not need to use the mutation observer to look at attributes any more.
We have a good system for monitoring attribute changes, so we no longer should need to use the `MutationObserver` to update the options every time an attribute changes (like selected-value).
This seems to have gotten rid of at least one UI glitch.
Highlight the next option once on is selected.
> Options being updated when there was no need

- dist/much-select-debug.js
- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- dist/much-select.js
- src/MuchSelect.elm
- src/OptionsUtilities.elm
- src/SelectedValueEncoding.elm
- src/much-select.js
- tests/Attributes/SelectedValue.elm
I was running into a bug while testing in the segment builder in the monolith.
It took a lot of testing to figure out what was going on. But, somehow something was triggering a `lightDomChange` when the the `<much-select>` _should_ have been in `events-only` mode. To solve this problem I added an extra check in the JavaScript for the `events-only` attribute. I should not need to do this here, but I don't think it's going to do any harm.
*There is still a mystery about how this can happen*. I wouldn't not have thought there would have been a way to do this, but I guess there is.
I also added a bunch more elm tests. I though (among other things) there might be a bug in how I was handling things when the `attributeChanged` port got called. I don't think that's the issue any more. I'm keeping …
> selected-value attribute (in the light DOM) is being updated when it should not be

- dist/much-select-debug.js
- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- dist/much-select.js
- src/Demo.elm
- src/MuchSelect.elm
- src/much-select.js
When testing in the monolith, we need to be able to support setting the `allow-custom-options` attribute to `true`, with out `true` being the actual hint.
> Add the ability to specify a custom option hint to the Elm demo.

- tests/Attributes/selected-value-encoding.test.html
Make sure that if all the following are true, the event looks right:
- `<much-select>` is in single select mode
- json selected value encoding
> Single Value JSON encoded selected value unit test

- src/much-select.js
Follow up to: https://github.com/DripEmail/much-select-elm/pull/226
Some parts of the app make use of the `change` event while other parts use the `input`, canonical the light DOM normally dispatches both, so we should follow suit.
> also dispatch input event on selected-value change

- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- dist/site/elm-demo.js
- src/MuchSelect.elm
If the select is disabled, do not add focus events on mouse down/up.
> Do not focus if input is diabled

- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- src/OptionList.elm
- tests/Option/CustomOptions.elm
To fix this I had to change up some of the logic and that broke some unit tests having to do with merging options. I think I solved by by making the `selectOptions` function a bit more complicated. It's behavior seems pretty sensible so I think it's OK.
But I can't help but wonder if the options that are coming in to be selected should already have a selected index on them.
> custom selected options always get a selected value index of 0

- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- scripts/build-minified-worker.sh
- scripts/build.sh
- src/MuchSelect.elm
- src/Option.elm
- src/OptionList.elm
When we convert from custom html to datalist we need to convert over the types of the options and the option lists. That wasn't happening so some of the utility functions were not working either.
> 245 datalist add button listeners not always working

- dist/much-select-debug.js
- dist/much-select.js
- src/much-select.js
When reviewing the JS debouncing code. I see we have 2 debounce functions.
It looks like we can get rid of one, no problem.
> JS Debouncing: Why have 2 when 1 will do

- site/demo-styles.css
This related to #132 and #133 but it's only a very small chunk of the work.
> Styling the demo site

- dist/much-select-debug.js
- dist/much-select.js
- examples/focus-on-demand.html
- site/events.html
- soupault.toml
- src/much-select.js
Add an example that shows how to call `focus()`, which will focus the `<much-select>`.
> Adding the `focus()` function to `MuchSelect`.

- dist/much-select-elm-debug.js
- dist/much-select-elm.js
- run-pty.json
- src/MuchSelect.elm
- src/SelectedValueEncoding.elm
Addresses: [GG-327](https://dripcom.atlassian.net/browse/GG-327)
Partial fix for commas in much select options. The issue comes up because we are using comma separated encoding for the selected value in most places. We get the selected value by splitting on `,`.
This updates comma separated encoding to skip spitting on `,` for single selects. A single select should only have one selected value, so there is no need to split in that case.
A more general fix would probably require switching to JSON encoding everywhere.
[GG-327]: https://dripcom.atlassian.net/browse/GG-327?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Comma in values fix

- package-lock.json
- package.json
`elm-format` is already referenced in the code, we just didn't include it in our dev dependencies.
> Adding elm-format to our npm packages
