public/clear-button.html
public/index.html
src/Main.elm
src/much-select.js

Adding a clear button. Adding some display logic around showing the loading indicator, or the dropdown indicator, or the clear button.

Clear button

---

public/demo-styles.css
src/Main.elm
src/much-select.js

Lots of changing having to do with styles, mostly things that simplify things. There are still things to fix, but I think this is going in the right direction.

Adjusting styles

---

src/Main.elm
src/much-select.js

We'll say this fixed #5 - sure there's probably more we could do, but this should take care of things pretty well.

Dropdown footer

---

README.md
public/multi-select.html
src/Main.elm
src/Option.elm
src/much-select.js

Multi select features 
- delete key #53 
- custom options #57 
There's also some additional documentation.

Multi select features

---

dist/elm-main-debug.js
dist/elm-main.js
dist/much-select-debug.js
dist/much-select.js
package-lock.json
package.json
public/selected-value-encoding.html
src/Main.elm
src/Ports.elm
src/much-select.js

Fixing an issue where the JSON encoding of a single value should just be a string.

Single Select JSON encoded values fix

---

README.md

Getting this up-and-running locally again and ran into some confusion around node version.
Hopefully this clears that up for future me (and others 😆 )

Document asdf and node version in README

---

public/initial-value-examples/async-loading-options-with-an-initial-value-smaller.html
public/initial-value-examples/async-loading-options-with-an-initial-value.html
public/initial-value-examples/async-loading-options-with-mulit-select-and-an-initial-value-smaller.html
public/initial-value.html
src/Option.elm
src/much-select.js
tests/Option/AddingOptions.elm

There was still some strange behavior when adding options asynchronously, this should iron that out.
I added some unit tests and some additional examples. With these examples I'm trying out a new format where the examples show up in iFrames so we can also look at the examples on their own.

92 bug with how options are updated from the dom

---

.github/workflows/tests.yml
elm.json
package-lock.json
package.json
review/elm.json
review/src/ReviewConfig.elm

We've got some npm packages to upgrade and it's about time we install elm-review.

Upgrade packages and install elm-review

---

public/demo-styles.css
public/multi-select-examples/custom-options.html
public/multi-select.html
src/Main.elm

Fixing a bug where bluring the in multi-select mode with custom options turned on caused the dropdown to get into a bad state.

98 filtering with custom options

---

src/Main.elm
src/much-select.js

For a while not I've been a bit concerned about just how many message get handled when something simple, like a value getting selected happens. To address this, there are some ports now that have a "debounce" on them, where there's a small delay, and if the port gets called right away again it cancels the first call, and we wait again.
We don't "dong" until the "ding" has had a chance to finish.
I'm pretty sure what's going on with the flashing is virtual DOM updates, so in theory `Html.Lazy` should sort that out. I did a little bit of lazy html, but we might have to do more.

106 UI flashes when we options are selected

---

package-lock.json
package.json
public/index.html
src/Main.elm
src/much-select.js

I'm afraid I might be doing too much here, but here we go.
- Tweaking the markup to put the dropdown outside of the value-casing
- Version bump to 0.9.0
- Fixing some examples

Release 0.9.0

---

public/attributes.html
public/event-logger.js
public/events.html
public/example-partials/multi-select-blur-or-unfocused-value-change.html
public/multi-select-blur-or-unfocused-value-change.html
src/much-select.js

Adding a example to help sort this out. I think things are mostly working.
There were some extra events getting fired when the value was cleared.

129 An example to try things out

---

public/add-options-to-a-multi-select-not-including-the-selected-value.html
public/custom-options.html
public/example-partials/add-options-to-a-multi-select-not-including-the-selected-value.html
public/example-partials/much-select-ready-event.html
public/initial-value.html
src/Main.elm
src/Option.elm
src/much-select.js
tests/FilteringOptions/MaxNumberOfDropdownItems.elm
tests/FilteringOptions/OptionSearcher.elm
tests/Option/CustomOptions.elm

This should fix issues in #134 #135 #140.
There's also a bunch of misc stuff in here, like fixing things in the sandbox site, typos, and some refactoring.

135 the first items is getting selected when adding a custom option

---

src/Option.elm
tests/Option/CustomOptions.elm

The dropWhile function was a poor choice, filter is the right thing.

---

src/Option.elm
src/OptionSearchFilter.elm
src/OptionSearcher.elm
tests/FilteringOptions/OptionSearcher.elm

I don't think I understood how the filtering worked when I initially thought I had handicapped the group in #140

144 changing group and description weighting

---

src/Main.elm
src/OutputStyle.elm
src/Ports.elm
src/SelectionMode.elm

This work is not done yet, but we needed to plugin some placeholder code here so we wouldn't get javascript exceptions.
Here's the follow up issue: https://github.com/DripEmail/much-select-elm/issues/158

Add Port for Output Style Change

---

src/Demo.elm
src/much-select.js

Adding the placeholder attribute to the Elm demo. This helps with reproducing #174

Adding the placeholder attribute to the Elm demo.

---

src/Main.elm
src/Ports.elm
src/SelectionMode.elm
src/much-select.js
tests/IntegrationTests/DisplayingOptions.elm

Fixing a bug where the placeholder was not showing up in multi select. This turned out to be a problem of not finishing a previous refactor.
I also updated the model a bit, to more closely model the the state of an attribute being...
- not present
- present but empty
- present and not empty

174 placeholder is not alwasys showing up

---

src/Main.elm
tests/Attributes/OutputStyle.elm
tests/Events/KeyPress.elm

Addressing a TODO and adding a unit test for it.
Fixing a typo in a test file name.

192 tighten up OutputStyleChanged

---

public/example-partials/disabled-much-select.html
src/Main.elm

When a datalist much-select is disabled it should still show any selected values.
This should work in single and multi select mode.

Disabled datalist should show value

---

src/Demo.elm

This appears to be working now. I'll bet #203 got fixed as part of #207.

Adding the ability to blank out the value to elm demo.

---

run-pty.json
scripts/build-dev.sh
scripts/build.sh

Fixing a few little things that have been on my mind.
- better indicators in run-pty for at least a couple things
- adding elm test so they get run on the regular
- fixing a warning that would pop up during the build because the directory build/gen was being used by 2 different build scripts.

Improving bilding

---

dist/much-select-elm-debug.js
dist/much-select-elm.js
dist/site/elm-demo.js
examples/max-dropdown-items.html
examples/max-number-of-dropdown-items.html
src/MuchSelect.elm
tests/Attributes/loading.test.html

The previous version of much-select supported setting the `loading` attribute to the string "false". This adds that behavior back and adds a unit test for it.
We also just added some unit tests for the loading attribute.

loading attribute behavior

---

devbox.json
devbox.lock

Adding Devbox to this fork for consistency.

Adding Devbox
